### PR TITLE
103 split

### PR DESCRIPTION
**Pull request by fmauch**
In version 1.0.3 packages got restructured making this necessary

### CODE REVIEW

**Comment by fmauch** [comment]
This currently fails due to missing numpy include dirs:

```
In file included from /usr/include/eigenpy/fwd.hpp:14,
                 from /usr/include/eigenpy/eigenpy.hpp:9,
                 from /home/mauch/.cache/yay/ros-melodic-moveit-ros-planning-interface/src/moveit-1.0.3/moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp:53:
/usr/include/eigenpy/numpy.hpp:15:10: fatal error: numpy/numpyconfig.h: No such file or directory
   15 | #include <numpy/numpyconfig.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

The missing header is inside `/usr/lib/python3.8/site-packages/numpy/core/include/numpy` so I guess, we need to add `-DPYTHON_INCLUDE_DIR=/usr/include/python3.8` to the cmake flags?

**Comment by acxz** [comment]
Would that work? Does the error still appear on the master branch of this package? Maybe the fix is the a commit that has already been merged upstream.

**Comment by fmauch** [comment]
No, it does not. Quite obviously, as the missing header is in the package's subfolder, not insode `/usr/include/python3.8`. I wasn't thinking enough.

**Comment by acxz** [comment]
I'm a bit confused on your updates to the eigenpy patch.
It would be proper if we apply a patch that upstream has already approved.
Do you mind trying this one: https://github.com/ros-planning/moveit/commit/bc9c4ce5ec7ad8b37de9d9f2e6c77d4871e09c85.patch ?

**Comment by fmauch** [comment]
This would be the same as I did in my first attempt to remove the patch completely. The patch you linked, is also in commit https://github.com/ros-planning/moveit/commit/9aaad286ae7e2b8b521238a0a2859c5e2613c629 which is included in version 1.0.3.

It seems that the `find_package` command does not export the numpy include directories properly. Should we instead try to get this fixed upstream in eigenpy?

**Comment by acxz** [comment]
Yeah maybe it is an eigenpy issue. Even though the patch you created works, since the root problem is somewhere else lets try to fix it there, instead of here.

> Does the error still appear on the master branch of this package?

Where you able to confirm this?

**Comment by fmauch** [comment]
I just checked, the same error appears on the master branch.

**Comment by acxz** [comment]
You could make an issue titled build error to get more visibility than in a PR discussion. I would look into it but im a bit busy this week.

**Pull request merged**
